### ISSUE TITLE
Configuration Management Refactoring

### ISSUE THREAD

**Issue by MoiKeyboard** [MoiKeyboard/moi-bkr#14]
# Current Pattern (to be replaced)
```python
self.market_config = config.get("market_analysis", {})
config_dir = self.market_config.get("data_dir")
base_dir = config_dir.get(self.env, DEFAULT_PATHS[self.env])
```

## Target Pattern
```python
self.config.get("market_analysis.data_dir.dev")  # Direct path access
```

## Tasks
1. Configuration Structure
   - [ ] Define a flat naming convention (e.g., dot notation: "market_analysis.data_dir.dev")
   - [ ] Create a mapping of all configuration paths used in the application
   - [ ] Document the complete configuration schema

2. Configuration Loading
   - [ ] Create a configuration loader class/module
   - [ ] Implement flattening of nested YAML structure
   - [ ] Add default values handling
   - [ ] Add environment-specific overrides

3. Configuration Access
   - [ ] Create standardized access patterns
   - [ ] Define error handling for missing configs
   - [ ] Implement type validation
   - [ ] Add configuration caching if needed

4. Migration Steps
   - [ ] Identify all configuration access points in code
   - [ ] Create mapping of old->new configuration paths
   - [ ] Update configuration files structure
   - [ ] Update code to use new access pattern

## Example Target Structure
```yaml
# Flattened config structure example
market_analysis.provider: "yahoo"
market_analysis.lookback_days: 100
market_analysis.data_dir.dev: ".data"
market_analysis.data_dir.prod: "/opt/trading_bot/data"
market_analysis.tickers: ["AAPL", "MSFT", "GOOGL"]
tws.host: "127.0.0.1"
tws.port: 7497
tws.client_id: 1
```

## Benefits
- More readable configuration access
- Easier to track configuration dependencies
- Simpler maintenance and updates
- Better IDE support for config paths
- Clearer documentation of available settings

## Considerations
- Backward compatibility during migration
- Performance impact of flattening
- Configuration validation
- Environment variable overrides
- Default values handling
