### ISSUE TITLE
Brainstorm best approach to environment config managment

### ISSUE THREAD

**Issue by MoiKeyboard** [MoiKeyboard/moi-bkr#16]
Current approach to determining environment is using environment variable
`export ENV_MODE=prod`
This is very messy with variable assigned to environment specified on tail-end key of config.yaml
```
market_analysis:
  provider: yahoo  # yahoo or ib
  lookback_days: 100
  data_dir:
    dev: ".data"
    prod: "/opt/trading_bot/data"

```
